### ISSUE TITLE
[RFE] Button to clear all stats from the Stats graph.

### ISSUE THREAD

**Issue by bzvonar** [RHsyseng/t5g-field-support-team-utils#101]
Would be nice if there was a 'Clear All' button for the Stats graph, when you just want to see a couple of stats.

And I suppose a 'Set All' would be logical as well, but I can always just refresh the page if I want that.

**Comment by dcritch** [comment]
Thanks @adhil0 !

**Comment by bzvonar** [comment]
Thanks @adhil0 - so much less clicking now : )
