### ISSUE TITLE
[RFE/NIT] Coloured Badge Labels for Yes/No Columns (e.g. Escalated/Priolist, Watchlist)

### ISSUE THREAD

**Issue by bzvonar** [RHsyseng/t5g-field-support-team-utils#103]
Considering doing the same thing you did for https://github.com/RHsyseng/t5g-field-support-team-utils/issues/56 for the yes/no columns - I would say just making the "Yes" a red badge would probably be sufficient.

**Comment by patrickeasters** [comment]
In a discussion today, it was determined this may be misleading when customer temperature is added. Are we good with just bolding "Yes" or should we keep it colored in the interim.

**Comment by dcritch** [comment]
I personally vote **bold**
