### ISSUE TITLE
[RFE] Jira Display: show Jira Telco Priority

### ISSUE THREAD

**Issue by bzvonar** [RHsyseng/t5g-field-support-team-utils#211]
The Telco Priority is one of the following labels: 

- telco-priority-1
- telco-priority-2
- telco-priority-3
- telco-priority-4

Request is to display this alongside Priority on the Jira line (and Severity, if you add that).

*But* maybe hold off on doing this since we are in the process of getting telco priority moved to the Internal Whiteboard field.

**Comment by bzvonar** [comment]
Hi @adhil0 - coming back to this - we ended up getting a new field altogether called "RH Private Keywords", where the 4 priorities are like so... 

Telco:Priority-1
Telco:Priority-2
Telco:Priority-3
Telco:Priority-4 

This was introduced last September, and I haven't really done too much yet to stamp out the use of labels, but will do eventually.

Meanwhile, I'd love it if we could entertain adding this to the case dashboard now, based on this RH Private Keywords field, as it will help give visibility as to whether the case and bug are aligned.

**Comment by adhil0** [comment]
@bzvonar Sure, I'll take a look at this and see what data we can display as is

**Comment by bzvonar** [comment]
Sounds good, thanks - let me know if you need any info/whatever.
