### ISSUE TITLE
Clean Up CI/CD

### ISSUE THREAD

**Issue by adhil0** [RHsyseng/t5g-field-support-team-utils#46]
Ex: If files in `bin` are changed. run sync scripts, if files in `dashboard` are changed, run those scripts etc.

**Comment by dcritch** [comment]
I think we can close this one @adhil0 ? We have it for the dashboard. I don't think we care so much about `bin` since those are run manually whenever the person wants

**Comment by adhil0** [comment]
Agreed, closing
