### ISSUE TITLE
[RFE] Use colored badge labels to the severity property of the cases

### ISSUE THREAD

**Issue by ptrnull** [RHsyseng/t5g-field-support-team-utils#56]
Can we use use colored labels to enhance the severity of the cases?
For example, for a "Severity: High" use the red badge label, for a "Severity: Low" use a blue badge label.
This will be useful to enable filtering in the future and also to enable the user to locate the cases really fast based on the colors.
Bootstrap already provides a way to do that: https://www.w3schools.com/bootstrap/bootstrap_badges_labels.asp

**Comment by dcritch** [comment]
PR has merged, so closing the issue
