### ISSUE TITLE
Filtering and Sorting Improvements

### ISSUE THREAD

**Issue by dcritch** [RHsyseng/t5g-field-support-team-utils#76]
A couple of suggestions we've gotten to improve filtering/sorting:
- Filter by Case Account, Escalations and Watchlist
- Chain sort order so sort by severity AND escalated

**Comment by adhil0** [comment]
> - Chain sort order so sort by severity AND escalated


Looks like multi-column sorting is already [enabled](https://datatables.net/examples/basic_init/multi_col_sort.html), so maybe we could sort by both of these columns by default and add some sort of message to tell users to use shift+click to sort by multiple columns?

**Comment by dcritch** [comment]
yup, that makes sense to me.

one thing that was also brought up before is having a URL to a specific sort order. so people can share a link to a specific view. is that do able with the datatables stuff? so ideally if I click by 'escalation' the URL might change to have a query param like say `.../severity?sortby=escalated` or something like that.

**Comment by adhil0** [comment]
Looks like this is possible -  https://datatables.net/blog/2017-07-24 -  But the URL won't be automatically updated

**Comment by dcritch** [comment]
Okay, that should be alright. I think if we have a good default sort order, it will be less important anyway

**Comment by bzvonar** [comment]
It's a bit of a hack I guess, but I can filter on escalated cases only if I put Yes in the filter box - works for me : ).

**Comment by dcritch** [comment]
Addressed by #82 #87 #93 #98
