### ISSUE TITLE
[RFE] Permalink Capability

### ISSUE THREAD

**Issue by bzvonar** [RHsyseng/t5g-field-support-team-utils#86]
A low priority, 'for your consideration', request - the ability to create a permalink to the 'All Telco5G Cards' table with whatever sorting and filtering is in effect (and when I say filtering, I currently mean whatever's in the search box).

If you do consider doing this, and are going to add filtering, I would wait until you've finished the filtering before looking at this (unless it's trivial to do, of course).

**Comment by dcritch** [comment]
Great stuff @adhil0 !

**Comment by bzvonar** [comment]
That is cool - nice : )
