### ISSUE TITLE
Improve Readability of Dashboard

### ISSUE THREAD

**Issue by adhil0** [RHsyseng/t5g-field-support-team-utils#9]
Based on feedback from the team, we could use CSS, Bootstrap, or Patternfly to add colors or different font sizes to improve the look of the dashboard

**Comment by ptrnull** [comment]
If using bootstrap, would be really cool to have a way to highlight the active li element, something like:
https://www.codeply.com/go/bp/Xf2w5JHJhR
https://getbootstrap.com/docs/4.0/components/list-group/#javascript-behavior
For tracking the active item during the review of the content.

**Comment by dcritch** [comment]
Fixed by #26 ?

**Comment by ptrnull** [comment]
Yes, good job @adhil0 ,  closing the issue.
